jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ./.github/actions/checkout

      - name: Set up PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: '8.3'
       
      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: ./.github/actions/checkout

      - name: Set up PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: '8.3'
      
      - name: Install dependencies
        run: composer install

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Sync the application files to the server
          rsync -avz --delete --no-t --exclude 'tests' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH
          # Restart Apache if needed
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"
